name: ASCII art contributions

on:
  # Run multiple times per day to create the pattern
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'  # Every 4 hours
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  ascii-art-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1
      
      - name: Update files and create commits
        env:
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_NAME: ${{ github.actor }}
        run: |
          # Configure git
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          
          # Function to create a commit by updating existing files
          create_commit() {
            # Update timestamp file
            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
            echo "Last Updated: $timestamp" > timestamp.txt
            
            # Update counter file with random stats
            count=$((RANDOM % 1000))
            echo "ASCII Art Pattern Stats" > stats.txt
            echo "Timestamp: $timestamp" >> stats.txt
            echo "Pattern: ILLIA" >> stats.txt
            echo "Iteration: $count" >> stats.txt
            echo "Status: Active" >> stats.txt
            
            git add timestamp.txt stats.txt
            git commit -m "ASCII Art: ILLIA pattern update - $timestamp"
          }
          
          # Create multiple commits by updating the same files
          for i in {1..4}; do
            create_commit
            sleep 1
          done
          
          # Push all commits
          git push origin ${{ github.event.repository.default_branch }}

        shell: bash
