name: ASCII Art Contributions - ILLIA

on:
  # Run multiple times per day to create the pattern
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'  # Every 4 hours
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  ascii-art-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1
      
      - name: Create commits for ASCII art pattern
        env:
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_NAME: ${{ github.actor }}
        run: |
          # Configure git
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          
          # Get current date info
          current_date=$(date +"%Y-%m-%d")
          current_hour=$(date +"%H")
          
          # Function to create a commit
          create_commit() {
            timestamp=$(date +"%Y%m%d_%H%M%S")
            echo "ASCII Art Contribution - $timestamp" > "contribution_$timestamp.txt"
            git add .
            git commit -m "ASCII Art: ILLIA pattern - $timestamp"
          }
          
          # Create multiple commits based on the pattern needed
          # This creates a denser pattern during "active" days
          for i in {1..4}; do
            create_commit
            sleep 1
          done
          
          # Push all commits
          git push origin ${{ github.event.repository.default_branch }}

        shell: bash
